### ISSUE TITLE
ow configuration help

### ISSUE THREAD

**Issue by pin32** [roobbb/owserver#5]
hi I'm trying to get the container to work on an openhab home automation system on rpi4.
I did several tests with ordinary installation with partial functioning and after long battles I gave up.
with the discovery of this container system the desire to make my 1w network work returned to me.
I have a busmaster ds9490 device that connects to the ds18b20 sensor bus, I loaded the container on the server and monitoring it with portainer it is running, on the log I have this result:

![immagine](https://github.com/roobbb/owserver/assets/107401551/1dcfa8ff-9e27-4d82-a828-378e4b1b52c8)

from the wiki I learn that the configuration file is located in /etc/owfs.conf, I created this file with the default contents.
I tried to change the configuration according to the normal installation (no container) doing endless tests without appreciable results.
I'm probably missing a few steps to get the system working.
Is there a complete guide to do this?
Can you give me some advice on how to make the container work.
Thank you.

Joseph

**Comment by roobbb** [comment]
Hello Joseph.

I have tested the container with the Denkovy adapter and a Rpi3. I do not have a ds9490 and have no experience with Portainer. But I think it should even run in your setup. I tried to document the needed steps in the wiki of this repo here.
With the standard config you do not need to deal with owfs.conf - but it requires a device as /dev/onewire, set by an udev-rule --> not applicable for your ds9490 (?).
I don't know how Portainer starts the container and sets the required parameters.

The steps are as follows (all on cli of your Rpi e.g. via ssh):
- connect the one wire stick to your Rpi and check with `dmesg | grep usb` if it connects fine
- find out the USB id with `ls -lah /dev/serial/by-id` what shows the full path and the mapped device (helpful if you have more than one device connected)
- check if an instance of onewire container is still/ already running via `docker ps` and if so stop it with `docker stop ...`
- remove the container
- setup a simple startscript file on your Rpi by `touch ~/startOWServerTest.sh` and make it executable: `sudo chmod +x ~/startOWServerTest.sh`
- put in the start command like this and save the file

```
docker run -d \
   --name=owserver \
   --net=mytestnet \
   --restart=always \
   -v /etc/localtime:/etc/localtime:ro \
   --device=<your_usb-path_found_above> \
   -e OW_DEVICE=<your_usb-path_found_above> \
roobbb/owserver
```
- start the container by `~/startOWServerTest.sh`
- check the logs with `docker logs owserver`

- check if the owserver inside the container could start successfully:
```
docker exec -it owserver /bin/bash
service owserver status
```

- if not, keep inside the container and check if the USB-device is available there: `ls -lah /dev/serial/by-id`

Passing your own owfs.conf comes in handy when your setup is not covered by the simple default onewire config (in most cases  not needed). In every case it is important to pass through the USB-device from your host into the container.
It seems Portainer should be configured first to run the container properly as described here: https://docs.portainer.io/user/docker/containers/advanced

When owserver starts fine by the simple script, then you will have your needed parameters for Portainer and know it should run.

Kind regards
roobbb

**Comment by pin32** [comment]
Thanks for the reply
I made the udev rule and I have the device:

![immagine](https://github.com/roobbb/owserver/assets/107401551/90ff0339-a8a1-4db1-9926-7d933531accc)


docker run -d \
   --name=owserver \
   --net=host \
   --restart=always \
   -v /etc/localtime:/etc/localtime:ro \
   --device=/dev/onewire \
   -e OW_DEVICE=/dev/onewire \
roobbb/owserver

I removed the configuration file in /etc and started creating the container with these parameters:

![immagine](https://github.com/roobbb/owserver/assets/107401551/a4077e07-fbd6-4c93-94d6-4704ad603824)

the container is loaded correctly

![immagine](https://github.com/roobbb/owserver/assets/107401551/d18f832f-8032-4657-8142-aea4950a15ae)

from the container log I see this

**Comment by pin32** [comment]
clearly I don't get any response if I try to browse the web page...
I need some more help

**Comment by roobbb** [comment]
Hello.

> I removed the configuration file in /etc and started creating the container with these parameters:
> 
> ![immagine](https://user-images.githubusercontent.com/107401551/278823792-a4077e07-fbd6-4c93-94d6-4704ad603824.png)

I cannot see any parameters in this screenshot. What does it show here?

> the container is loaded correctly

I'm afraid it isn't, because of the error messages from sed and owserver.

Could you please start and enter the container as described in my post above and paste in here the results of these three commands?

`ls -lah /dev/one*`

`cat /etc/owfs.conf`

`cat /dev/onewire`

The webpage only comes up when the onewire service could start without errors. What we are looking for is the reason why the owserver and owhttpd services do not start. At first the container should be started clear and fine without any other software. Then we could check if owserver can access your USB-device step by step.

Kind regards
roobbb

**Comment by pin32** [comment]
![image](https://github.com/roobbb/owserver/assets/107401551/b332010a-e4a5-4849-b482-f12289ec842d)
these are the results of the commands.
thanks to the availability

**Comment by pin32** [comment]
root@openhab:/# cat /etc/owfs.conf

# Sample configuration file for the OWFS suite for Debian GNU/Linux.
#
#
# This is the main OWFS configuration file. You should read the
# owfs.conf(5) manual page in order to understand the options listed
# here.

######################## SOURCES ########################
#
# With this setup, any client (but owserver) uses owserver on the
# local machine...
! server: server = 127.0.0.1:4304
#
# ...and owserver uses the real hardware, by default fake devices
# This part must be changed on real installation
# server: FAKE = DS18S20,DS2405
#
# USB device: DS9490
#server: usb = all
#
# Serial port: DS9097
server: device = /dev/onewire
#
# owserver tcp address
#server: server = 192.168.10.1:3131
#
# random simulated device
#server: FAKE = DS18S20,DS2405
#
######################### OWFS ##########################
#
#mountpoint = /mnt/1wire
#allow_other
#
####################### OWHTTPD #########################

http: port = 2121

####################### OWFTPD ##########################

ftp: port = 2120

####################### OWSERVER ########################

server: port = 127.0.0.1:4304

root@openhab:/#

**Comment by pin32** [comment]
root@openhab:/# ls -lah /dev/one*
crw-rw-r-- 1 root plugdev 189, 2 Oct 29 15:41 /dev/onewire
root@openhab:/#

**Comment by pin32** [comment]
root@openhab:/# cat /dev/onewire
$       2        
         
@@               @@root@openhab:/#

**Comment by pin32** [comment]
It seems like the container sees the device and the standard configuration file, but it doesn't seem to get the correct information from the device.
is there anything I can do?
Thank you

**Comment by pin32** [comment]
![image](https://github.com/roobbb/owserver/assets/107401551/366c83d7-a3de-4f82-bc4f-2da8cd6a5d11)

this is the udev rule I use

**Comment by roobbb** [comment]
Yes, looks good so far. I'm not pretty sure. The group was in my case "dialout" - I don't know if it makes a difference.
You could try to pass the original /dev/ttyUSB-device into the container instead of /dev/onewire and try the checks again.

If `cat /dev/tty???` looks better, you could keep inside the container and edit the /etc/owfs.conf like this:
remove # before  `server: usb = all` 
and comment with # before `server: device = /dev/onewire` or rather `server: device = /dev/tty???
`

Save file and restart services directly
```
service owserver restart
service owhttpd restart
service owhttpd status
```
Hopefully the communication will then work 😀 

In some cases the USB-device gets captured by modemmanager or brltty on the host. Both can safely be removed (on the host dmesg would show some hints).

It is even possible to debug owserver and get more hints by entering this command inside the container:
`/usr/bin/owserver --debug --foreground --error_print=2 --error_level=9 -c /etc/owfs.conf`
You can see then what device will be used and if it can be reset. 
If this looks OK, maybe owhttpd only has a problem. Sometimes it can help to bind the service to the host's IP address instead of 127.0.0.1. This can even be done directly inside the container by editing the owfs.conf and restarting services again.

Kind regards
roobbb

**Comment by pin32** [comment]
`DEBUG MODE
libow version:
        3.2p4
  DEBUG: ow_inotify.c:(37) Added /etc/owfs.conf to the watch list
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:1) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:2) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:3) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:4) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:5) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:6) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:7) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:8) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:9) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:10) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:11) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:12) Program=Not server, Option=server, Value=127.0.0.1:4304
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:13) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:14) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:15) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:16) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:17) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:18) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:19) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:20) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:21) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:22) Program=server, Option=device, Value=/dev/onewire
  DEBUG: ow_opt.c:(342) Configuration file (/etc/owfs.conf:22) Option device recognized as device. Value=/dev/onewire
  DEBUG: ow_regex.c:(24) Reg Ex expression </> compiled to 0x7f9ab8ca90
  DEBUG: ow_regex.c:(24) Reg Ex expression <^[:digit:]+$> compiled to 0x7f9ab8cad0
  DEBUG: ow_regex.c:(24) Reg Ex expression <[:digit:]{1,3}\.[:digit:]{1,3}\.[:digit:]{1,3}\.[:digit:]{1,3}> compiled to 0x7f9ab8cb10
  DEBUG: ow_regex.c:(24) Reg Ex expression <^ftdi:> compiled to 0x7f9ab8cb50
  DEBUG: ow_regex.c:(24) Reg Ex expression <:> compiled to 0x7f9ab8cb90
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:23) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:24) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:25) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:26) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:27) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:28) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:29) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:30) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:31) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:32) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:33) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:34) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:35) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:36) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:37) Program=http, Option=port, Value=2121
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:38) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:39) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:40) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:41) Program=ftp, Option=port, Value=2120
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:42) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:43) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:44) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:45) Program=server, Option=port, Value=127.0.0.1:4304
  DEBUG: ow_opt.c:(342) Configuration file (/etc/owfs.conf:45) Option port recognized as port. Value=127.0.0.1:4304
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:46) Program=, Option=, Value=
  DEBUG: ow_daemon.c:(170) main thread id = 548056860128
CONNECT: ow_dnssd.c:(81) Zeroconf/Bonjour is disabled since dnssd library isn't found
   CALL: ow_parsename.c:(174) path=[]
  DEBUG: owlib.c:(77) Global temp limit 0C to 100C (for fake and mock adapters)
  DEBUG: ow_ds9097U.c:(471) Attempt 0 of 3 to initialize the DS9097U
CONNECT: ow_serial_open.c:(45) [Inappropriate ioctl for device] Cannot get old port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
  DEBUG: ow_ds9097U.c:(471) Attempt 1 of 3 to initialize the DS9097U
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
  DEBUG: ow_ds9097U.c:(471) Attempt 2 of 3 to initialize the DS9097U
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
  DEBUG: ow_ds9097U.c:(456) Could not initialize the DS9097U even after several tries
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
CONNECT: owlib.c:(121) Cannot detect DS2480 or LINK interface on /dev/onewire.
CONNECT: ow_serial_open.c:(45) [Inappropriate ioctl for device] Cannot get old port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(66) [Inappropriate ioctl for device] Cannot get existing port attributes: /dev/onewire
CONNECT: ow_serial_open.c:(154) [Inappropriate ioctl for device] Cannot set port attributes: /dev/onewire
DEFAULT: owlib.c:(130) Cannot detect DS9097 (passive) interface on /dev/onewire.
  DEBUG: ow_serial_free.c:(39) COM_close: flush
  DEBUG: ow_serial_free.c:(41) COM_close: restore
CONNECT: ow_serial_free.c:(43) [Inappropriate ioctl for device] Cannot restore port attributes: /dev/onewire
DEFAULT: owlib.c:(52) No valid 1-wire buses found
  DEBUG: ow_exit.c:(17) Exit code = 1
   CALL: ow_lib_close.c:(21) Starting Library cleanup
   CALL: ow_lib_stop.c:(22) Clear Cache
  DEBUG: ow_cache.c:(295) Flipping cache tree (purging timed-out data)
  DEBUG: ow_cache.c:(313) flip cache. tdestroy() will be called.
  DEBUG: ow_cache.c:(295) Flipping cache tree (purging timed-out data)
  DEBUG: ow_cache.c:(313) flip cache. tdestroy() will be called.
   CALL: ow_lib_stop.c:(24) Closing input devices
   CALL: ow_lib_stop.c:(26) Closing output devices
   CALL: ow_lib_close.c:(42) Finished Library cleanup
  DEBUG: ow_lib_close.c:(50) Libraries closed`

**Comment by pin32** [comment]
I don't understand anything... see if you can understand something.
Thank you

**Comment by pin32** [comment]
![image](https://github.com/roobbb/owserver/assets/107401551/56b5340b-b530-4514-953e-b9d96ea1a8ea)

![image](https://github.com/roobbb/owserver/assets/107401551/d9cfcaf9-7141-4647-ba21-58499e233c9f)

![image](https://github.com/roobbb/owserver/assets/107401551/fff3369f-8764-414c-87fa-b1a0970396aa)

I tried to activate the server that was commented and the server was activated (on the container log), and by activating the fake server it works.
at this point you should only understand how to manage the hardware device.
I tried to modify the udev rule by naming the serial device as tty-onewire ca with the "cat" command, I always get the same result.

![image](https://github.com/roobbb/owserver/assets/107401551/8d7d0d96-a78c-4e88-b2c6-3190fee5756b)

do you have any idea?

**Comment by roobbb** [comment]
Hello.

With activated fake device it should always work and the webif should appear. But it only tells us the ow-services and the container itself are OK. 
I think in your case there is an issue with the communication between owserver and USB-Device.

In my opinion it can have those reasons:
software
- device blocked by other software like modemmanager or brltty
- device blocked by other container e.g. other running instance of owserver, portainer etc.
- problems with udev-rule like group or something like that*
- particular instruction inside owfs.conf needed 
- accidentally activated option what makes trouble in addition

hardware
- USB-stick too close to the Rpi4 so its Radios make trouble - an USB extension cord may help
- insufficient power on USB-bus - a active USB hub could solve that
- stick "hangs" - maybe replugging helps
- faulty cable to the 1-wire nodes - maybe connecting only 1 node first by a short cable will help
- faulty USB-device

But it's hard to guess. You could try to eliminate each possible issue step by step.

*Please leave the udev rule as it is or deactivate it. The tty-device is always there but I simply don't know its actual name. Maybe /dev/ttyUSB0 or /dev/ttyACM0 or something else. You can find out with `dmesg | grep tty` or `ls -lah /dev/serial/by-id/*` on the hosts side. Just plug in and replug and retry the commands to make sure the device is surely your DS9490. Please paste in the final result here.
And then pass this tty??? device to the container (remove the container first) and retry all the checks inside the container. Just to omit the udev-rule.

Or try another udev-rule to get access for users (without symlink):
`SUBSYSTEMS=="usb", ATTRS{idVendor}=="04fa", ATTRS{idProduct}=="2490", NAME="bus/usb/$env{BUSNUM}/$env{DEVNUM}", GROUP="users", MODE="0660"`
and retry all the checks with that.

Further you could create a simple owfs.conf on your host (e.g. ~/owfs.example) with this content:
```
! server: server = localhost:4304
server: usb = all
server: device = /dev/tty???
http: port = 2121
ftp: port = 2120
server: port = localhost:4304
```
And create + start the container like so:
```
docker run -d \
   --rm \
   --name=owserver \
   --net=testnet \
   --network-alias myowserver \
   -p 2121:2121 \
   -v /etc/localtime:/etc/localtime:ro \
   -v ~/<yourpath_to_owfs.example>:/root/.local/share \
   --device=/dev/tty??? \
   -e CUSTOM_CONFIG_ENABLED=1 \
   -e CUSTOM_CONFIG_FILE=/root/.local/share/owfs.example \
roobbb/owserver:latest
```
Substitute /dev/tty??? in both by the one you've found before and substitute <yourpath_to_owfs.example> to you actual path.
With that you don't need to edit owfs.conf inside the container each time, you can do that on hosts side and start then the container.

Isolating the actual issue is more or less a trial and error thing what you even would suffer with owserver installed directly onto your Rpi.

I'm afraid I am gradually running out of ideas.

Best of luck
roobbb

**Comment by pin32** [comment]
I tried to install the standard version of owfs and it works normally, I also found the solution to the double readings online due to a bug on raspberry.
but I would like to port owfs containers, but I don't have the skills to do the necessary troubleshooting...
considering that on a software level it works, and the hardware works, what could I touch? I know you don't have the same testing hardware as me, but if you want we could try to solve the problem.
HI

**Comment by roobbb** [comment]
Hello.

I can try to help, but I do not know your setup and have not much more information than you entered here. 
Unfortunately I do not have any owserver compliant hardware anymore, so I cannot test with any hardware. So it seems to be more a guessing gaming 😀

When you say it works fine installed on the host, then it should be easy to get the container working too, because owserver inside is installed the same way. The only important thing is to pass the USB device through with the same authorization as on the host-side.

Could you please attach here your owfs.conf that owserver was working with on the host-side? I would like to see what parameters and device you have been using there.
And please paste in here the result of `ls -lah /dev/serial/by-id/*` on the host-side and what is the result when you let run owserver on the host again and enter this command `owserver --v`. In the container I get this:
```
owserver version:
	3.2p4
libow version:
	3.2p4
```
Best regards
roobbb

**Comment by pin32** [comment]
# Sample configuration file for the OWFS suite for Debian GNU/Linux.
#
#
# This is the main OWFS configuration file. You should read the
# owfs.conf(5) manual page in order to understand the options listed
# here.

######################## SOURCES ########################
#
# With this setup, any client (but owserver) uses owserver on the
# local machine...
! server: server = localhost:4304
#
# ...and owserver uses the real hardware, by default fake devices
# This part must be changed on real installation
#server: FAKE = DS18S20,DS2405
#
# USB device: DS9490
server: usb = all
#
# Serial port: DS9097
server: device = /dev/ttyUSB2
#
# owserver tcp address
#server: server = 192.168.10.1:3131
#
# random simulated device
#server: FAKE = DS18S20,DS2405
#
######################### OWFS ##########################
#
mountpoint = /mnt/1wire
allow_other
#
####################### OWHTTPD #########################

http: port = 2121

####################### OWFTPD ##########################

ftp: port = 2120

####################### OWSERVER ########################

server: port = localhost:4304

**Comment by roobbb** [comment]
Could you please set it in a code block or as attachment to your post? It is not readable good that way. Thank you.

**Comment by pin32** [comment]
![immagine](https://github.com/roobbb/owserver/assets/107401551/3f6fca5a-cf83-4e19-9a11-0861169442ee)

![immagine](https://github.com/roobbb/owserver/assets/107401551/a988e65e-497a-4716-bd93-38425f86c533)

**Comment by pin32** [comment]
extract of owfs.conf


! server: server = localhost:4304
server: usb = all
server: device = /dev/ttyUSB2
mountpoint = /mnt/1wire
allow_other
http: port = 2121
ftp: port = 2120
server: port = localhost:4304

**Comment by pin32** [comment]
How do you use the "code" button?

**Comment by roobbb** [comment]
this way:
![code tags](https://github.com/roobbb/owserver/assets/43150729/6e83d666-3fd1-483a-a462-ab9328ab1bfe)


OK, in your working owfs.conf you are using /dev/ttyUSB2, but this device is not in in the list of the devices. Is the DS9490 not connected? What are the other devices?

**Comment by pin32** [comment]
`ttyUSB2 is assigned with the udev rule, ttyUSB0, ttyUSB1 are used by two other containers always assigned with the udev rule.
the owfs server was running when I ran the commands.
thank you very much`

**Comment by roobbb** [comment]
Hello.
What happens when you change in owfs.conf from /dev/ttyUSB2 to /dev/onewire and restart your lokal running owserver? Does it still work then?
Kind regards
roobbb

**Comment by pin32** [comment]
![immagine](https://github.com/roobbb/owserver/assets/107401551/c71a417c-5467-4fae-9ddc-d789a514aa79)
there are no differences in operation by renaming the device to "onewire"
thank you very much

**Comment by roobbb** [comment]
Hi.

Ok, then let's try again. Please disable your udev rule and unplug+replug your DS9490, so the device ttyUSB2 appears again. Switch back to ttyUSB2 in your owfs.conf on the host side.
Please make then a copy of your working owfs.conf and name it owfs.test. It should have the content you have posted before:
```
! server: server = localhost:4304
server: usb = all
server: device = /dev/ttyUSB2
mountpoint = /mnt/1wire
allow_other
http: port = 2121
ftp: port = 2120
server: port = localhost:4304
```
Then stop any running owserver instance and make sure the device /dev/ttyUSB2 is there and not blocked by any service or any udev rule.

Start the container by this command:
`docker run -d --rm --net=host --name=owserver -v <path_to_your_file>/owfs.test:/etc/owfs.test --device=/dev/ttyUSB2 -e CUSTOM_CONFIG_ENABLED=1 -e CUSTOM_CONFIG_FILE=/etc/owfs.test roobbb/owserver:latest`
*Substitute <path_to_your_file> by your path where your owfs.test is actually located.

Throw this command and check if the webpage is up.
`docker exec -it owserver owhttpd --debug`
Paste in the result here.

Best regards
roobbb

**Comment by pin32** [comment]
ok I'll do the test.
I'll clarify one question: the ds9490r device isn't listed in /dev if I don't put a udev rule. even when I have ttyUSB2 it is a consequence of udev rule.
so if I don't put a rule I don't know which path to use to locate it.
Thank you

**Comment by pin32** [comment]
![immagine](https://github.com/roobbb/owserver/assets/107401551/f5145050-690d-40d6-a098-a934263ee60f)
![immagine](https://github.com/roobbb/owserver/assets/107401551/86f605aa-49c5-4259-90fb-32f14b961270)
it does not work
 Thank you

**Comment by roobbb** [comment]
> the ds9490r device isn't listed in /dev if I don't put a udev rule. even when I have ttyUSB2 it is a consequence of udev rule. so if I don't put a rule I don't know which path to use to locate it. 

I do not understand that. When you don't have any udev-rule the device should appear a other device - you can find out which one when you use dmesg as I wrote in my posts above. Anyway.

What are the outputs of:
`docker exec -it owserver cat /etc/owfs.conf`
`docker exec -it owserver ls -la /dev*`
`docker ps -a`
`docker inspect owserver`

Kind regards
roobbb

**Comment by pin32** [comment]
`pin32@openhab:~ $ docker exec -it owserver cat /etc/owfs.conf
# Sample configuration file for the OWFS suite for Debian GNU/Linux.
#
#
# This is the main OWFS configuration file. You should read the
# owfs.conf(5) manual page in order to understand the options listed
# here.

######################## SOURCES ########################
#
# With this setup, any client (but owserver) uses owserver on the
# local machine...
! server: server = localhost:4304
#
# ...and owserver uses the real hardware, by default fake devices
# This part must be changed on real installation
#server: FAKE = DS18S20,DS2405
#
# USB device: DS9490
server: usb = all
#
# Serial port: DS9097
server: device = /dev/ttyUSB2
#
# owserver tcp address
#server: server = 192.168.10.1:3131
#
# random simulated device
#server: FAKE = DS18S20,DS2405
#
######################### OWFS ##########################
#
mountpoint = /mnt/1wire
allow_other
#
####################### OWHTTPD #########################

http: port = 2121

####################### OWFTPD ##########################

ftp: port = 2120

####################### OWSERVER ########################

server: port = localhost:4304
`

**Comment by pin32** [comment]
pin32@openhab:~ $ docker exec -it owserver ls -la /dev*
total 4
drwxr-xr-x 5 root root       340 Nov  8 19:47 .
drwxr-xr-x 1 root root      4096 Nov  8 19:47 ..
lrwxrwxrwx 1 root root        13 Nov  8 19:47 fd -> /proc/self/fd
crw-rw-rw- 1 root root      1, 7 Nov  8 19:47 full
drwxrwxrwt 2 root root        40 Nov  8 19:47 mqueue
crw-rw-rw- 1 root root      1, 3 Nov  8 19:47 null
lrwxrwxrwx 1 root root         8 Nov  8 19:47 ptmx -> pts/ptmx
drwxr-xr-x 2 root root         0 Nov  8 19:47 pts
crw-rw-rw- 1 root root      1, 8 Nov  8 19:47 random
drwxrwxrwt 2 root root        40 Nov  8 19:47 shm
lrwxrwxrwx 1 root root        15 Nov  8 19:47 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root root        15 Nov  8 19:47 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root root        15 Nov  8 19:47 stdout -> /proc/self/fd/1
crw-rw-rw- 1 root root      5, 0 Nov  8 19:47 tty
crw-rw-r-- 1 root plugdev 189, 2 Nov  8 19:47 ttyUSB2
crw-rw-rw- 1 root root      1, 9 Nov  8 19:47 urandom
crw-rw-rw- 1 root root      1, 5 Nov  8 19:47 zero

**Comment by pin32** [comment]
![immagine](https://github.com/roobbb/owserver/assets/107401551/3654e5b7-5609-4dff-9daa-6a51d86eb41e)

**Comment by pin32** [comment]
[file.txt](https://github.com/roobbb/owserver/files/13300890/file.txt)


Thank you

**Comment by roobbb** [comment]
Hello.

Thank you. Unfortunately I cannot find any reason why it doesn't work. The configs look good. I have no idea.

Best regards
roobbb

**Comment by roobbb** [comment]
You're welcome. Maybe it's worth a try to check some other owserver-containers available on the docker-hub. One may have no problem or already a solution.

Kind regards
roobbb
